version: '3'
services: 
  site:
    container_name: my_blog
    command: jekyll serve --watch --host 0.0.0.0 --config _config.yml,_config_docker.yml
    image: jekyll/jekyll:3.8
    volumes: 
      - .:/srv/jekyll
    ports: 
      - 4000:4000
    environment:
      - JEKYLL_ENV=docker